id: A77AAFF05
title: Concise Daily Practice of Vajrasattva
type: translation
pechas:
- I4EF44FAE
- I43A09701
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:39:00.804989
  last_modified_at: 2023-01-04 11:39:00.804997
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I4EF44FAE/99D6: 5A56
  I43A09701/9FB9: 5A56
